#!/usr/bin/env python3
#
# minigaia.dr2 - Víctor R. Ruiz <rvr@infoastro.com>
# Converts Gaia DR2 CSV files to binary format
#


# Gaia DR2 data model
# Extracted from: https://gea.esac.esa.int/archive/documentation/GDR2/Gaia_archive/chap_datamodel/sec_dm_main_tables/ssec_dm_gaia_source.html

columns = {
    # Key : [ Description, Type, Unit ]
    'solution_id': ['Solution Identifier', 'long', ''],
    'designation': ['Unique source designation (unique across all Data Releases)', 'string', ''],
    'source_id': ['Unique source identifier (unique within a particular Data Release)', 'long', ''],
    'random_index': ['Random index used to select subsets', 'long', ''],
    'ref_epoch': ['Reference epoch', 'double', 'Time[Julian Years]'],
    'ra': ['Right ascension', 'double', 'Angle[deg]'],
    'ra_error': ['Standard error of right ascension', 'double', 'Angle[mas]'],
    'dec': ['Declination', 'double', 'Angle[deg]'],
    'dec_error': ['Standard error of declination', 'double', 'Angle[mas]'],
    'parallax': ['Parallax', 'double', 'Angle[mas] '],
    'parallax_error': ['Standard error of parallax', 'double', 'Angle[mas] '],
    'parallax_over_error': ['Parallax divided by its error', 'float', ''],
    'pmra': ['Proper motion in right ascension direction', 'double', 'Angular Velocity[mas/year]'],
    'pmra_error': ['Standard error of proper motion in right ascension direction', 'double', 'Angular Velocity[mas/year] '],
    'pmdec': ['Proper motion in declination direction', 'double', 'Angular Velocity[mas/year] '],
    'pmdec_error': ['Standard error of proper motion in declination direction', 'double', 'Angular Velocity[mas/year] '],
    'ra_dec_corr': ['Correlation between right ascension and declination', 'float', 'Dimensionless[see description]'],
    'ra_parallax_corr': ['Correlation between right ascension and parallax', 'float', 'Dimensionless[see description]'],
    'ra_pmra_corr': ['Correlation between right ascension and proper motion in right ascension', 'float', 'Dimensionless[see description]'],
    'ra_pmdec_corr': ['Correlation between right ascension and proper motion in declination', 'float', 'Dimensionless[see description]'],
    'dec_parallax_corr': ['Correlation between declination and parallax', 'float', 'Dimensionless[see description]'],
    'dec_pmra_corr': ['Correlation between declination and proper motion in right ascension', 'float', 'Dimensionless[see description]'],
    'dec_pmdec_corr': ['Correlation between declination and proper motion in declination', 'float', 'Dimensionless[see description]'],
    'parallax_pmra_corr': ['Correlation between parallax and proper motion in right ascension', 'float', 'Dimensionless[see description]'],
    'parallax_pmdec_corr': ['Correlation between parallax and proper motion in declination', 'float', 'Dimensionless[see description]'],
    'pmra_pmdec_corr': ['Correlation between proper motion in right ascension and proper motion in declination', 'float', 'Dimensionless[see description]'],
    'astrometric_n_obs_al': ['Total number of observations AL', 'int', ''],
    'astrometric_n_obs_ac': ['Total number of observations AC', 'int', ''],
    'astrometric_n_good_obs_al': ['Number of good observations AL', 'int', ''],
    'astrometric_n_bad_obs_al': ['Number of bad observations AL', 'int', ''],
    'astrometric_gof_al': ['Goodness of fit statistic of model wrt along-scan observations', 'float', ''],
    'astrometric_chi2_al': ['AL chi-square value', 'float', ''],
    'astrometric_excess_noise': ['Excess noise of the source', 'double', 'Angle[mas]'],
    'astrometric_excess_noise_sig': ['Significance of excess noise', 'double', ''],
    'astrometric_params_solved': ['Which parameters have been solved for?', 'byte', ''],
    'astrometric_primary_flag': ['Primary or seconday', 'boolean', ''],
    'astrometric_weight_al': ['Mean astrometric weight of the source', 'float', 'Angle[mas^2]'],
    'astrometric_pseudo_colour': ['Astrometrically determined pseudocolour of the source', 'double', 'Misc[mu · m^-1]'],
    'astrometric_pseudo_colour_error': ['Standard error of the pseudocolour of the source', 'double', 'Misc[mu · m^-1]'],
    'mean_varpi_factor_al': ['Mean Parallax factor AL', 'float', ''],
    'astrometric_matched_observations': ['Matched FOV transits used in the AGIS solution', 'short', ''],
    'visibility_periods_used': ['Number of visibility periods used in Astrometric solution', 'short', ''],
    'astrometric_sigma5d_max': ['The longest semi-major axis of the 5-d error ellipsoid', 'float', 'Angle[mas]'],
    'frame_rotator_object_type': ['The type of the source mainly used for frame rotation', 'int', ''],
    'matched_observations': ['Amount of observations matched to this source', 'short', ''],
    'duplicated_source': ['Source with duplicate sources', 'boolean', ''],
    'phot_g_n_obs': ['Number of observations contributing to G photometry', 'int', ''],
    'phot_g_mean_flux': ['G-band mean flux', 'double', 'Flux[e-/s]'],
    'phot_g_mean_flux_error': ['Error on G-band mean flux', 'double', 'Flux[e-/s]'],
    'phot_g_mean_flux_over_error': ['G-band mean flux divided by its error', 'float', ''],
    'phot_g_mean_mag': ['G-band mean magnitude', 'float', 'Magnitude[mag]'],
    'phot_bp_n_obs': ['Number of observations contributing to BP photometry', 'int', ''],
    'phot_bp_mean_flux': ['Integrated BP mean flux', 'double', 'Flux[e-/s]'],
    'phot_bp_mean_flux_error': ['Error on the integrated BP mean flux', 'double', 'Flux[e-/s]'],
    'phot_bp_mean_flux_over_error': ['Integrated BP mean flux divided by its error', 'float', ''],
    'phot_bp_mean_mag': ['Integrated BP mean magnitude', 'float', 'Magnitude[mag]'],
    'phot_rp_n_obs': ['Number of observations contributing to RP photometry', 'int', ''],
    'phot_rp_mean_flux': ['Integrated RP mean flux', 'double', 'Flux[e-/s]'],
    'phot_rp_mean_flux_error': ['Error on the integrated RP mean flux', 'double', 'Flux[e-/s]'],
    'phot_rp_mean_flux_over_error': ['Integrated RP mean flux divided by its error', 'float', ''],
    'phot_rp_mean_mag': ['Integrated RP mean magnitude', 'float', 'Magnitude[mag]'],
    'phot_bp_rp_excess_factor': ['BP/RP excess factor', 'float', ''],
    'phot_proc_mode': ['Photometry processing mode', 'byte', ''],
    'bp_rp': ['BP - RP colour', 'float', 'Magnitude[mag]'],
    'bp_g': ['BP - G colour', 'float', 'Magnitude[mag]'],
    'g_rp': ['G - RP colour', 'float', 'Magnitude[mag]'],
    'radial_velocity': ['Radial velocity', 'double', 'Velocity[km/s] '],
    'radial_velocity_error': ['Radial velocity error', 'double', 'Velocity[km/s] '],
    'rv_nb_transits': ['Number of transits used to compute radial velocity', 'int', ''],
    'rv_template_teff': ['Teff of the template used to compute radial velocity', 'float', 'Temperature[K]'],
    'rv_template_logg': ['logg of the template used to compute radial velocity', 'float', 'GravitySurface[log cgs]'],
    'rv_template_fe_h': ['Fe/H of the template used to compute radial velocity', 'float', 'Abundances[dex]'],
    'phot_variable_flag': ['Photometric variability flag', 'string', 'Dimensionless[see description]'],
    'l': ['Galactic longitude', 'double', 'Angle[deg]'],
    'b': ['Galactic latitude', 'double', 'Angle[deg]'],
    'ecl_lon': ['Ecliptic longitude', 'double', 'Angle[deg]'],
    'ecl_lat': ['Ecliptic latitude', 'double', 'Angle[deg]'],
    'priam_flags': ['flags for the Apsis-Priam results', 'long', 'Dimensionless[see description]'],
    'teff_val': ['stellar effective temperature', 'float', 'Temperature[K]'],
    'teff_percentile_lower': ['teff_val lower uncertainty', 'float', 'Temperature[K]'],
    'teff_percentile_upper': ['teff_val upper uncertainty', 'float', 'Temperature[K]'],
    'a_g_val': ['line-of-sight extinction in the G band, A_G', 'float', 'Magnitude[mag]'],
    'a_g_percentile_lower': ['a_g_val lower uncertainty', 'float', 'Magnitude[mag]'],
    'a_g_percentile_upper': ['a_g_val upper uncertainty', 'float', 'Magnitude[mag]'],
    'e_bp_min_rp_val': ['line-of-sight reddening E(BP-RP)', 'float', 'Magnitude[mag]'],
    'e_bp_min_rp_percentile_lower': ['e_bp_min_rp_val lower uncertainty', 'float', 'Magnitude[mag]'],
    'e_bp_min_rp_percentile_upper': ['e_bp_min_rp_val upper uncertainty', 'float', 'Magnitude[mag]'],
    'flame_flags': ['Flags for the Apsis-FLAME results', 'long', 'Dimensionless[see description]'],
    'radius_val': ['stellar radius', 'float', 'Length &amp; Distance[Solar Radius]'],
    'radius_percentile_lower': ['radius_val lower uncertainty', 'float', 'Length &amp; Distance[Solar Radius]'],
    'radius_percentile_upper': ['radius_val upper uncertainty', 'float', 'Length &amp; Distance[Solar Radius]'],
    'lum_val': ['stellar luminosity', 'float', 'Luminosity[Solar Luminosity]'],
    'lum_percentile_lower': ['lum_val lower uncertainty', 'float', 'Luminosity[Solar Luminosity]'],
    'lum_percentile_upper': ['lum_val upper uncertainty', 'float', 'Luminosity[Solar Luminosity]'],
}

